development:
  adapter: postgresql
  database: estudoprofite_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: estudoprofite_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: estudoprofite_production
  pool: 5
  timeout: 5000
