development:
  adapter: postgresql
  database: profite-study-api_development
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: profite-study-api_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: profite-study-api_production
  host: localhost
  pool: 5
  timeout: 5000
