development:
  adapter: sqlite3
  database: db/profite-study-api_development.sqlite3
  pool: 5
  timeout: 5000
  
test:
  adapter: sqlite3
  database: db/profite-study-api_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: profite-study-api_production
  host: localhost
  pool: 5
  timeout: 5000
